// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0c0Gh4XjKw2dINhYeq7HsyNtGfN0sNG0',
    appId: '1:828073095388:android:00434c08ff71be45258419',
    messagingSenderId: '828073095388',
    projectId: 'smartmeter-70845',
    databaseURL: 'https://smartmeter-70845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartmeter-70845.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpns9t1mAQb5qiqLinpqR3cZOToeJE9Ig',
    appId: '1:828073095388:ios:a4d40aaee6d20e3b258419',
    messagingSenderId: '828073095388',
    projectId: 'smartmeter-70845',
    databaseURL: 'https://smartmeter-70845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartmeter-70845.appspot.com',
    iosBundleId: 'com.example.albanitm',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAecvSoDbNNmGuLd7iALvqcBvFhIhpMV3k',
    appId: '1:828073095388:web:19fa915f92ab8474258419',
    messagingSenderId: '828073095388',
    projectId: 'smartmeter-70845',
    authDomain: 'smartmeter-70845.firebaseapp.com',
    databaseURL: 'https://smartmeter-70845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartmeter-70845.appspot.com',
    measurementId: 'G-S3EJJZ26D2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpns9t1mAQb5qiqLinpqR3cZOToeJE9Ig',
    appId: '1:828073095388:ios:a4d40aaee6d20e3b258419',
    messagingSenderId: '828073095388',
    projectId: 'smartmeter-70845',
    databaseURL: 'https://smartmeter-70845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartmeter-70845.appspot.com',
    iosBundleId: 'com.example.albanitm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAecvSoDbNNmGuLd7iALvqcBvFhIhpMV3k',
    appId: '1:828073095388:web:881f2aeef2487ba4258419',
    messagingSenderId: '828073095388',
    projectId: 'smartmeter-70845',
    authDomain: 'smartmeter-70845.firebaseapp.com',
    databaseURL: 'https://smartmeter-70845-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartmeter-70845.appspot.com',
    measurementId: 'G-KVDGVB5FV4',
  );

}